### PR TITLE
Deploy using travis-ci and git-ftp

### PR DESCRIPTION
**Pull request by christophebedard**
This is just to test automatic deployment to FTP server using travis-ci. Right now, Travis is set to build pull requests, so it will actually "build" and deploy.

However, once we get this working, we'll remove the option to build pull requests, thus we'll only deploy after pushes to master.

### CODE REVIEW

**Comment by christophebedard** [comment]
Travis seems to have issues with FTP 😐 https://github.com/travis-ci/travis-ci/issues/9347

**Comment by christophebedard** [comment]
Next solution is to use travis' container-based architecture, as this might help, apparently. This means `sudo` isn't available, so I'll have to try [using addons.apt.packages](https://docs.travis-ci.com/user/installing-dependencies/#Adding-APT-Packages). I've requested that `git-ftp` be [whitelisted](https://github.com/travis-ci/apt-package-whitelist): https://github.com/travis-ci/apt-package-whitelist/issues/4296

Edit: well, it seems to work anyway 🤔 https://travis-ci.org/elikos/website/builds/393867600#L415

**Comment by christophebedard** [comment]
Alright, I found the problem.
FTP indeed seems to work better on container-based architecture. However, it's using `trusty`, so therefore it has an old version of `git-ftp` (0.9.0), in which `remote-root` wasn't available.
The solution is to specify a full `ftp://` address and appending the `remote-root` at the end (e.g. `ftp://<host>/<remote-root>`).

**Comment by christophebedard** [comment]
@g-leclaire what do you think?

**Review by g-leclaire — APPROVED** [review]
Great, I don't have any experience with Travis CI but it's a good idea to have an automated deployment.

**Pull request merged**
